// ============================================================
// The fixed words of the Charter, in one place.
//
// WHY THIS FILE EXISTS. The Charter's standing text was written straight into
// the page that displays it. That was fine while the only way to read a Charter
// was to look at the screen. It stopped being fine the moment the Charter could
// also be downloaded, because a signed agreement whose copy says something
// different from the screen somebody signed is worse than no copy at all.
//
// So the parts that do not vary by engagement live here, as data, and both the
// screen and the document read them. One place to change, one place to be
// wrong, and no way for the two to drift apart quietly.
//
// WHAT IS NOT HERE. Anything that varies: the organisation, the funder, the
// parties, the dates, the conversation minimums, the signatures. Those come
// from the engagement's own record. This file is the method, and the method is
// the same for every client.
// ============================================================

/** How a decision travels from the work to the funder. Four steps, in order. */
export const EVIDENCE_CHAIN = [
  {
    step: 'Step 1 · Beneficiary',
    does: 'Generates the evidence',
    detail: 'Does the work and produces the real output, the audit, the conversations, the model, the pilots.',
  },
  {
    step: 'Step 2 · Coach',
    does: 'Guides and holds the standard',
    detail: 'Facilitates the session, tests the evidence, and authorises the block only when it truly holds.',
  },
  {
    step: 'Step 3 · Beneficiary ED',
    does: 'Signs it off',
    detail: 'The Executive Director puts their name to the decision, it is the organisation’s, not the coach’s.',
  },
  {
    step: 'Step 4 · Funder',
    does: 'Accepts it',
    detail: 'The funder accepts the evidence as meeting the standard for that deliverable.',
  },
]

/**
 * What the engagement asks of the organisation, by role.
 *
 * This is the section people actually need to read before they sign, because
 * it is the one that costs them something. It is deliberately specific: an
 * agreement that says "senior engagement" commits nobody to anything.
 */
export const COMMITMENT = [
  {
    role: 'Executive Director',
    asks: 'Attends the opening diagnostic in person, which cannot be delegated, and personally signs off all nine decision points. Present at the three readiness reviews. Makes the hard calls the process surfaces, including stopping services that do not pay.',
  },
  {
    role: 'Leadership team',
    asks: 'In the room for the working sessions and writes the outputs themselves. The coach facilitates; this is not a document handed to them to sign. Leads the second pilot round and delivers the final handover unaided.',
  },
  {
    role: 'Finance lead',
    asks: 'Attends every costing session and must be able to run the financial model unaided by the end of the viability block, demonstrated live. Owns the numbers thereafter.',
  },
  {
    role: 'Field and delivery team',
    asks: 'Conducts the real customer conversations and the live pilots, and follows a strict capture discipline. Client-facing practice is central: this is where the model is proven or broken.',
  },
  {
    role: 'Board',
    asks: 'The Chair, or a delegate, attends the opening diagnostic and signs it. The board approves the growth plan before it is committed.',
  },
]

/** The standing principle the whole method rests on. */
export const EVIDENCE_PRINCIPLE = [
  'Nothing is taken on trust. Every block is closed on evidence, not opinion, not activity, not a filled-in form.',
  'The evidence is generated by the organisation: its own service data, real customer conversations, real pilot deliveries, real numbers. The coach does not produce it for them; the coach guides the work and holds the standard.',
  'A block is complete only when the evidence is real and the agreed signal has genuinely been observed. Filled in is not the same as resolved.',
  'Every piece of evidence is logged in a single Evidence Library and referenced by number, so at any moment anyone can see what a decision was based on. That library is both the audit trail and, at the end, the organisation’s handover record.',
]

/** How the work is governed, and what stops it drifting. */
export const GROUND_RULES = [
  'The decision points are worked in order. A zone does not open until the one before it has been signed off, because a block opened early is a block worked without the decision behind it.',
  'A gate is closed by a signature, not by paperwork. Evidence submitted and awaiting a signature leaves the next zone shut.',
  'Momentum is reported honestly as green, amber or red. An engagement that is behind is more useful to everyone as an amber than as an optimistic green.',
  'Where a specific in this Charter needs to change for this engagement, it is changed before signing rather than worked around afterwards.',
]

/** Who owns what at the end, which is the question people ask last and worry about first. */
export const OWNERSHIP = [
  'The commercial model, the evidence and every output belong to the organisation. They are produced by its own people and they leave with them.',
  'The Grant-to-Commercial Viability Canvas™, the method, its tools and its materials remain the intellectual property of The Canvas Coach and are licensed for use during the engagement.',
  'The funder receives the evidence agreed in the Terms of Reference. Nothing else about the engagement is disclosed without the organisation’s agreement.',
]

/** What signing means, said once and said plainly. */
export const SIGNATURE_MEANING =
  'By signing, each party confirms they have read this Charter and commit to the responsibilities and the level of participation it sets out. Signatures apply to the version recorded here. If the Charter is edited afterwards, signing re-opens for everyone.'
