-- ============================================================
-- The organisation can attach its own evidence.
--
-- WHAT WAS INCONSISTENT. The row in evidence_library and the file attached to
-- it were governed by two different rules. A row could be written by anyone
-- working on their own engagement, which is right: the method says the evidence
-- is generated by the organisation, its own service data, its own customer
-- conversations, its own pilot deliveries. But the file could only be uploaded
-- by somebody with manage rights, which is the coaching team.
--
-- So the organisation could create the entry and not attach the thing. And
-- because the upload control is shown to anybody who can edit, they were shown
-- a button that always failed. Found by signing in as the head of an
-- organisation and trying to upload evidence for their own engagement.
--
-- WHAT CHANGES. Attaching and replacing a file follow the same rule as writing
-- the row it belongs to: you may do it for an engagement you are on. Deleting
-- stays with the coaching team, because removing evidence is not the same act
-- as adding it, and the coach holds the standard.
--
-- WHAT DOES NOT CHANGE. Reading is unchanged and cross-engagement isolation is
-- unchanged: the first path segment is the engagement, and can_view_client
-- decides. Checked before and after by signing in as the head of a different
-- organisation, who could reach none of it either way.
-- ============================================================

drop policy if exists "evidence insert" on storage.objects;
create policy "evidence insert"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'evidence'
    and public.can_view_client(public.evidence_object_client(name))
  );

drop policy if exists "evidence update" on storage.objects;
create policy "evidence update"
  on storage.objects for update
  to authenticated
  using (
    bucket_id = 'evidence'
    and public.can_view_client(public.evidence_object_client(name))
  )
  with check (
    bucket_id = 'evidence'
    and public.can_view_client(public.evidence_object_client(name))
  );

-- Deleting is deliberately left where it was. Adding evidence is the work;
-- removing it is a decision about the record.
